// GENERATED by scripts/gen-device-policy.js from shared/device-policy.json — DO NOT EDIT.
// Change the policy there and re-run the generator;
// server/appd/test/device-policy-cases.test.js fails if they have drifted apart.

package com.silencelen.huginn.device

/**
 * The policy as data. [DevicePolicy] is the reasoning; this is the table it reads.
 *
 * Generated so that this file and the headless runner cannot disagree — they are
 * the same rule expressed for two runtimes, and the one thing that must never
 * happen is for one of them to quietly grant more than the other.
 */
internal object DevicePolicyTable {
    val SCOPES: List<String> = listOf("generate", "look", "work", "own")
    val MODE_NEEDS: Map<String, String> = mapOf("ask" to "look", "act" to "work", "generate" to "generate")
    const val LOCK_DROPS_TO: String = "look"

    val STREAM_FLAGS: List<String> = listOf("-p", "--output-format", "stream-json", "--verbose", "--include-partial-messages")

    const val LOOK_ALLOWED: String = "Skill Read Glob Grep WebFetch WebSearch"
    const val LOOK_DENIED: String = "Bash Edit Write NotebookEdit"
    const val ACT_ALLOWED: String = "Skill Bash Read Edit Write Glob Grep WebFetch WebSearch"
    const val ACT_DENIED: String = ""

    const val REFUSAL_LOCKED: String = "this machine is locked, so it is read-only until someone unlocks it"
    const val REFUSAL_SCOPE: String = "this machine is set to {scope}, which cannot run {mode}"
    const val REFUSAL_ENGINE: String = "this machine has no local model engine, so it cannot run generate"

    /** Scopes that match only themselves, both ways. See shared/device-policy.json. */
    val EXCLUSIVE_SCOPES: List<String> = listOf("generate")
}
